// Base error type for all errors generated by this library.
export class LibraryError extends Error {
  constructor(message, options) {
    super(message, options);
    this.name = "LibraryError";
  }
}

// Raised when the implementation of this library has caused an error. For example, when a known edge case has not been
// handled.
export class ImplementationError extends Error {
  constructor(message, options) {
    super(message, options);
    this.name = "ImplementationError";
  }
}

// Raised when the library detects a user error.
export class UsageError extends LibraryError {
  constructor(message, options) {
    super(message, options);
    this.name = "UsageError";
  }
}

// Raised when an HTTP request causes an HTTP client error, i.e. for HTTP status codes >=300 and <=399.
export class RequestError extends LibraryError {
  constructor(message, { doc, response, ...options }) {
    super(message, options);
    this.name = "RequestError";
    Object.defineProperty(this, "doc", { value: doc });
    Object.defineProperty(this, "response", { value: response });
  }
}

// Raised when an HTTP response causes an error.
export class ResponseError extends LibraryError {
  constructor(message, { doc, response, ...options }) {
    super(message, { ...options, doc: { value: doc } });
    this.name = "ResponseError";
    Object.defineProperty(this, "response", { value: response });
  }
}

// Raised when served an HTTP server error, i.e. when it has a status code >= 500.
export class ServerError extends ResponseError {
  constructor(message, options) {
    super(message, options);
    this.name = "ServerError";
  }
}

// Raised when served an OK response with unexpected body content.
export class UnprocessableResponseError extends ResponseError {
  constructor(message, { response, ...options }) {
    super(message, {
      ...options,
      response,
      doc: {
        value: undefined,
        get() {
          throw new UsageError(
            `${this.name} does not have a doc property because the response could not be processed`,
          );
        },
      },
    });
    this.name = "ResponseBodyError";
  }
}

// Raised when served an HTTP response with a body and no content-type header.
export class MissingContentTypeError extends UnprocessableResponseError {
  constructor(message, options) {
    super(message, options);
    this.name = "MissingContentTypeError";
  }
}

// Raised when served an HTTP response with a body and an unrecognized content-type header.
export class UnexpectedContentTypeError extends UnprocessableResponseError {
  constructor(message, options) {
    super(message, options);
    this.name = "UnexpectedContentTypeError";
  }
}

// Raised when served an HTTP response body cannot be parsed as expected.
export class UnexpectedContentError extends UnprocessableResponseError {
  constructor(message, options) {
    super(message, options);
    this.name = "UnexpectedContentError";
  }
}
