name: Publish upon release

on:
  release:
    types: [released]

jobs:
  version:
    name: Get version ID
    runs-on: ubuntu-latest
    outputs:
      version-id: ${{ steps.get-version-id.outputs.version_id }}
    steps:
      - name: Get version ID
        id: get-version-id
        run: |
          node -e 'process.env.GITHUB_REF.startsWith("refs/tags/v") || process.exit(1)'
          echo "version_id=$(node -e 'console.log(process.env.GITHUB_REF.substring("refs/tags/v".length));')" >> "$GITHUB_OUTPUT"

  publish:
    name: Publish
    needs: version
    uses: ./.github/workflows/publish.yml
    secrets: inherit
    with:
      version-id: ${{ needs.version.outputs.version-id }}
